name: ci

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install package
        run: |
          pip install pip-tools>=7.4.0
          pip-sync requirements.txt dev-requirements.txt
          pip install .

      - name: Run commit-blocking lint checks
        run: |
          # Run pre-commit hooks. We have to be a little careful here with
          # pip-compile: if we ran it with --all-files, it would run
          # pip-compile on every pull, which would update the pinned
          # dependencies if any have changed - even if the requirements.in
          # files are unchanged.
          #
          # Run everything except pip-compile against all files
          SKIP=pip-compile pre-commit run --all-files
          # Run pip-compile - but only if requirements.in or
          # dev-requirements.in have changed in this pull request's diff.
          pre-commit run pip-compile --from-ref=$GITHUB_BASE_REF --to-ref=$GITHUB_HEAD_REF
